### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by DJorenby** [GreyCorbel/SIDCloner#3]
I have used sidcloner many times, but in one customer environment I'm getting access denied
I have triple checked all the requirements,
Trusts in place and working
Auditing enabled in source and target
TcpipClientSupport set in source
Migrate SidHistory set at the top of directory in the target.
I have also noted that there are no event logs created in the target when the access denied is generated.
I ran port query to check for blocked ports and I do see a problem with UDP 137, to you think that could be related?
I sure its environmental but I'm not sure where else to look.

Thanks
Dan

**Comment by gibazza** [comment]
In a production environment SIDCloner was reporting access denied but working as expected in a (not identical) dev environment. After much head scratching, I discover that source and target credentials in the netbios format (domain\sAMAccountName) worked in dev, but in prod only the UPN format worked.

Hope this helps. 

Cheers

Paul

**Comment by jformacek** [comment]
did you check permissions for accounts on both sides? 
Also, not sure if it may have been caused by credential format - you should use UPN format rather than domain\username, but on modern Windows versions, it returns `Inappropriate auth` error - but may return more generic `Access Denied` on older versions of Windows..
